server:
  port: 8080
management:
  endpoint:
    health:
      group:
        readiness:
          exclude:
            - diskSpace
            - livenessState
            - ping
          show-details: always
      probes:
        enabled: true