server:
  port: 80
management:
  endpoint:
    health:
      group:
        readiness:
          exclude:
            - diskSpace
            - livenessState
            - ping
          show-details: always
      probes:
        enabled: true
#  server:
#    port: 8080